INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('1', 'Juan Ladino', 'Se realizan Todo tipo de arreglos  relacionados con la plomeria, siempre con un trabajo excelente', '50000', 'plomero.jpg', '3', '1');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('2', 'Jorge Paz', 'Se arreglan todo tipo de fallos o instalaciones electricas con un precio bajo y muy buena calidad', '40000', 'electricista2.jpg', '4', '2');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('3', 'Nicolas Garcia', 'Aseador de Corazon, haciendo los trabajos con mucha dedicacion', '30000', 'aseador2.jpg', '1', '3');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('4', 'Francisco Jimenez', 'Se realizan Todo tipo de arreglos  relacionados con la plomeria, siempre con un trabajo excelente', '30000', 'plomero3.jpg', '6', '1');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('5', 'Daniela Arango', 'Se arreglan todo tipo de fallos o instalaciones electricas con un precio bajo y muy buena calidad', '38000', 'electricista1.jpg', '2', '2');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('6', 'Andrea Gonzales', 'Aseadora de Corazon, haciendo los trabajos con mucha dedicacion', '35000', 'aseadora3.jpg', '6', '3');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('7', 'Carolina Torrres', 'Se realizan Todo tipo de arreglos  relacionados con la plomeria, siempre con un trabajo excelente', '48000', 'plomera2.jpg', '4', '1');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('8', 'Camilo Heredia', 'Se arreglan todo tipo de fallos o instalaciones electricas con un precio bajo y muy buena calidad', '50000', 'electricista3.jpg', '2', '2');
INSERT INTO `GoService`.`gogers` (`id`, `fullName`, `description`, `price`, `image`, `experience`, `categories_id`) VALUES ('9', 'Juanita Hernandez', 'Aseadora de Corazon, haciendo los trabajos con mucha dedicacion', '28000', 'aseadora1.webp', '3', '3');

INSERT INTO `GoService`.`users` (`id`, `name`, `lastName`, `email`, `password`, `avatar`, `rol`) VALUES ('1', 'Nico', 'Garcia', 'nico.garcia@gmail.com', '1234', 'avatar_1643136647038.jpg', '1');
INSERT INTO `GoService`.`users` (`id`, `name`, `lastName`, `email`, `password`, `avatar`, `rol`) VALUES ('2', 'Fran', 'Paz', 'jorge@gmail.com', '1234', 'avatar_1643136613635.jpg', '1');
INSERT INTO `GoService`.`users` (`id`, `name`, `lastName`, `email`, `password`, `avatar`, `rol`) VALUES ('3', 'Juan', 'Ladino', 'juan@gmail.com', '1234', 'avatar_1640134962012.jpg', '1');
INSERT INTO `GoService`.`users` (`id`, `name`, `lastName`, `email`, `password`, `avatar`, `rol`) VALUES ('7', 'camilo', 'lad', 'juanc.ladinog@gmail.com', '1234', 'avatar_1640131607337.jpg', '9');
